name: 05-1-Events Filters and Activity Types
on:
   pull_request:
     types:
      - opened
      - synchronize
     branches:
      - main
jobs:
  echo:
    run: echo " PR open or syncronize will make it run"