name: 09-Using FUnctions
on:
  pull_request:
  workflow_dispatch:
jobs:
  echo1:
      runs-on: ubuntu-latest
      steps:
          - name: Print PR Title
            run: echo "${{github.event.pull_request.title}}"
          - name: Print PR Labels
            run: | 
               cat << EOF  
               echo "${{toJSON(github.event.pull_request.labels)}}"
               EOF
          - name: Bug fix Step
            if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix')}}
            run: echo " I am bug fix Step"
          - name: Sleep for 20 Sec
            run: sleep 20
          - name: Failing Step
            run: exit 1
          - name: I will be Skipped
            if: ${{success()}}
            run: echo "I will be skipped"
          - name: I will be execute
            if: ${{failure()}}
            run: echo "I will proint if any previous step fails"
          - name: I will be execute
            if: ${{!cancelled()}}
            run: echo "I will proint if any previous step fails"
          - name: I will be execute when cancelled
            if: ${{cancelled()}}
            run: echo "I will proint if any previous step fails"