name: Working with Inputs
on:
  workflow_dispatch:
      dry-run:
        type: boolean
        default: false
        description: "Skip deployment and only print build output"
      target:
        type: environment
        required: true
        description: "Which envirnment the workflow will target"
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        description: "Release from which to build and deploy"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Build
         run: echo " Building fron tag ${{inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: inputs.dry-run == false
    steps:
       - name: Build
         run: echo " Building fron tag ${{inputs.tag}}"