name: 12-Working with Outputs
on: 
  workflow_dispatch:
    inputs: 
        build-status:
            type: choice
            options:
                - success
                - failure
            default: success
jobs:
    build:
      outputs:
        build-status: ${{ step.build.output.status }}
      runs-on: ubuntu-latest
      steps:
          - name: Print GITHUB_OUTPUT path
            run: echo "$GITHUB_OUTPUT"
          - name: Build
            id: build
            run: echo "${{ status=inputs.build-status.options}}" >> $GITHUB_OUTPUT
    deploy:
      runs-on: ubuntu-latest
      needs: build
      if: ${{ needs.build.output.build-status == success}}
      steps:
          - name: Deploy
            run: echo "Deploying"
         